version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4"

    steps:
      - run: git clone --depth 1 --recurse_submodules git@github.com:StrongAI/strongai.git
      - run: git clone --depth 1 git@github.com:StrongAI/xcode.git
      - run: xcodebuild -project xcode/Intelligence.xcodeproj -target StrongAI•Type•Union•Test
      - run: ./xcode/build/Release/StrongAI•Type•Union•Test
workflows:
  version: 2
  test:
      jobs:
        - build-and-test
